### ISSUE TITLE
No external trigger events detected?

### ISSUE THREAD

**Issue by alandente11** [berndpfrommer/metavision_ros_driver#10]
I'm trying to use the Trigger In feature on a Prophesee Gen4 IMX636, but something is not working. I can run rostopic echo and view the events from the sensor, but rostopic echo /event_camera/trigger returns nothing. I have attached a copy of my launch file, trigger_pins.yaml (I modified to include hal_plugin_imx636_evk4), and a screenshot of what happens when I try to see if external trigger events are being received. I'm sure my triggering system works correctly because I can watch the external trigger events get processed using the Python calls for Metavision SDK and OpenEB.

![echo_pic](https://user-images.githubusercontent.com/113273466/191813018-39e66bca-cd98-438b-ad30-0e9bee9b1cc9.png)
[trigger_pins.pdf](https://github.com/berndpfrommer/metavision_ros_driver/files/9628120/trigger_pins.pdf)
[new_test_copy.pdf](https://github.com/berndpfrommer/metavision_ros_driver/files/9628131/new_test_copy.pdf)

**Comment by berndpfrommer** [comment]
We have not tested on Gen4. Have you tried loopback triggering to see if that works?
Maybe the author @k-chaney of the trigger code can offer suggestion?

**Comment by lbristiel-psee** [comment]
@berndpfrommer about your suggestion "Have you tried loopback triggering to see if that works?", not that EVK4 does not provide Trigger Out interface, so using loopback to test Trigger In can not be done with this EVK. (we recently refreshed the Sync Interface doc page where this is mentioned/explained: https://docs.prophesee.ai/stable/hw/manuals/timing_interfaces.html#trigger-in-configuration).

**Comment by k-chaney** [comment]
The trigger pins must be configured in the loaded yaml file. I do not believe the EVK4 pins are in the default `trigger_pins.yaml` file. Here is the example file: https://github.com/berndpfrommer/metavision_ros_driver/blob/a3c0fe226442a46fbf66a660e7284dc4304316b8/config/trigger_pins.yaml#L25

**Comment by alandente11** [comment]
The files I attached to my issue (above but in .pdf) include an additional entry in the trigger_pins.yaml file for the EVK4 using the detected "Plugin Software Name" which is hal_plugin_imx636_evk4. At the end of the .yaml file I added:

hal_plugin_imx636_evk4:
      external: 0
      loopback: 6

Doing all this is what gives me the issue I posted. Is this what you mean @k-chaney?

**Comment by berndpfrommer** [comment]
Andreas has figured out what's going on:
https://github.com/berndpfrommer/event_array_tools/issues/3#issuecomment-1308940006
Will look into it once I have Gen4 sensor in hand.

**Comment by berndpfrommer** [comment]
Closing for now. Please reopen if this is still an issue.
