### ISSUE TITLE
How to save event data?

### ISSUE THREAD

**Issue by linmingyuan** [berndpfrommer/metavision_ros_driver#20]
Hi, I want to record events and save them in a .txt/.h5 file. I use ROS1 and:
``` bash
rosbag record /event_cam/events
```
How can I read the .bag file and save events.
I fail to use [bag_decode_example.py](https://github.com/berndpfrommer/event_array_msgs/blob/master/python/bag_decode_example.py):
![Screenshot+from+2023-03-02+21-37-04](https://user-images.githubusercontent.com/34370514/222444478-4afa8741-d695-4a52-8c46-42062eb80d98.png)

**Comment by berndpfrommer** [comment]
Please try this repository and let me know how it goes:

https://github.com/berndpfrommer/event_array_py

**Comment by linmingyuan** [comment]
It works! Thanks for your reply!
