### ISSUE TITLE
Metavision SDK v4

### ISSUE THREAD

**Issue by stensalumets** [berndpfrommer/metavision_ros_driver#21]
Hello!

Are there plans to implement this driver for Metavision SDK version 4 as well. I'm using the corner detector there, but it seems that this driver, that I'd want to use, is not compatible with the v4 that is required for the corner detector.

Can't find this file during catkin build:
#include <metavision/hal/facilities/i_device_control.h>

Which I assume is due to different versioning.

**Comment by berndpfrommer** [comment]
Please pull from master and let me know if you hit any snags.
