### ISSUE TITLE
ros time  to external  evt message 

### ISSUE THREAD

**Issue by skylin008** [berndpfrommer/metavision_ros_driver#46]
Thank you shared this impressive project.  There's a RGB camera , for sync the  RGB camera , I want to put ros time to external EVT message, how to solve this issue. Thanks!

**Comment by berndpfrommer** [comment]
The ROS event messages have a header stamp that corresponds to *host time*, which should be synchronized with your RGB camera time stamps (assuming your event and RGB cameras are attached to the same host).
Inside the event messages there are the events, but they have a different timestamp (*sensor time*) which is not synchronized with anything. But by decoding the time stamp of the first event you can get the relationship between the message header stamps and the event time. Please see the discussion [here](https://github.com/ros-event-camera/event_camera_codecs?tab=readme-ov-file#event-time-stamps) and [here](https://github.com/ros-event-camera/event_camera_py?tab=readme-ov-file#about-timestamps).
