### ISSUE TITLE
 Error setting roi for Gen 41 sensor. 

### ISSUE THREAD

**Issue by mosfe** [berndpfrommer/metavision_ros_driver#5]
hello,when I install all the packages and run the command with roslaunch metavision_ros_driver driver_node.launch,the warning shows that [HAL][WARNING] Error setting roi for Gen 41 sensor, why is this problem? My hardware camera is not compatible with this peoject?
Hope your answer.

**Comment by berndpfrommer** [comment]
It works with the Gen4 sensor. Could you please post the launch file you are using? Thanks!

**Comment by mosfe** [comment]
![2](https://user-images.githubusercontent.com/95094143/190181682-1788f3c4-8eb0-4bb8-841a-1b3d9e643b1d.png)
![1](https://user-images.githubusercontent.com/95094143/190181704-f367c3ef-e70c-4b2e-a74f-316b51796ed7.png)

**Comment by mosfe** [comment]
I do not modify the codes and obey the instructions on the project, but my operating system is ubuntu 18.04 and ros version is melodic not noetic, maybe this matter?

**Comment by berndpfrommer** [comment]
Pushed a commit that hopefully fixes this. Can you pull from master again and retry?

**Comment by mosfe** [comment]
Thanks a lot,is works！

**Comment by mosfe** [comment]
![3](https://user-images.githubusercontent.com/95094143/190295198-d7d647f6-c344-4c60-ba08-ef5e188bbbee.png)
hello，when I pull from master and retry，it works and I get the event data I want，but the two errors are merged，do they have negative influence on the running？

**Comment by berndpfrommer** [comment]
The bias error has no consequences.
The missing calibration file will mean that the published camerainfo is junk. You probably don't care about that.
